### ISSUE TITLE
TypeError: Cannot read property 'oneOfType' of undefined

### ISSUE THREAD

**Issue by gilnetoglartek** [one-more/react-cron-builder#2]
On Runkit, I ran the following code (here: https://npm.runkit.com/react-cron-builder):

require("react-dom")
require("react/package.json"); // react is a peer dependency. 

require("lodash/package.json"); // lodash is a peer dependency. 
var reactCronBuilder = require("react-cron-builder")

After running it, I encounter the error in the title, pointing to the file react-cron-builder/dist/bundle.js (line 11)
This also happened on my local code, without any other message.

**Comment by one-more** [comment]
published next version - should work now. let me know about result

**Comment by gilnetoglartek** [comment]
It now works, thanks.

Just as a curiosity: is it possible to change the CSS properties of this component? I wanted to use the functionality, but not necessarily the interface. Is there a way to separate these?

Thanks.

**Comment by one-more** [comment]
you can override styles in your css, or do not include bundle.css file and write completely new styles, or fork repo and change src/cron-builder.styl
