### ISSUE TITLE
App crashed when clearing   all  selected values   and  click generate 

### ISSUE THREAD

**Issue by SojinAntony** [one-more/react-cron-builder#6]
App crashed when clearing all selected values and click generate 

![img a](https://user-images.githubusercontent.com/35334346/58558371-4349bd00-823e-11e9-80f8-f1c22719a036.png)

![Screenshot from 2019-05-29 18-26-28](https://user-images.githubusercontent.com/35334346/58558907-9708d600-823f-11e9-82b4-b9bde91478a5.png)

someone, please help

**Comment by one-more** [comment]
fixed in 1.0.4 version
