### ISSUE TITLE
Inconsistency in the buttons in the section periodically

### ISSUE THREAD

**Issue by jomarquez21** [one-more/react-cron-builder#7]
In the section periodically when you change between `minutes` and `hours` the values of `every` and `on` are also changed, this only happens when previously you had already changed between `every` and `on`.

Is there a way that these values do not change?

**Comment by one-more** [comment]
If you select same value `every` or `on` for both `minutes` and `hours` it'll work as expected

**Comment by jomarquez21** [comment]
Attached a video to reproduce the bug

[Storybook.webm.zip](https://github.com/one-more/react-cron-builder/files/3294539/Storybook.webm.zip)

**Comment by one-more** [comment]
`every/on` option selected is being remembered separately for `minutes` and `hours`

**Comment by jomarquez21** [comment]
Thanks for the response @one-more!
Regardless the remember feature, the issue I'm trying to expose is that the `Every`/`On` control should remain unchanged when I click the `minutes` control. Currently, it changes from `On` to `Every` in that case. I take some screenshots when the required steps to reproduce what I'm reporting here, but to resume; what I was expecting is to configure the execution at minute 1, every day:
**Step 1 (first form render without changes)**:
![step1](https://user-images.githubusercontent.com/16705169/59935724-0b383300-9414-11e9-9270-c36f646dc1d4.png)
**Step 2**:
![step2](https://user-images.githubusercontent.com/16705169/59935828-4470a300-9414-11e9-86df-f7c49dc75e7d.png)
**Step 3**:
![step3](https://user-images.githubusercontent.com/16705169/59935837-489cc080-9414-11e9-99e7-49e178b53226.png)
**Step 4 (the problem occurs here)**:
![step4](https://user-images.githubusercontent.com/16705169/59935849-4e92a180-9414-11e9-9ca0-b67fcfea31d9.png)

Please let me know if there is something I'm missing about this behavior.

**Comment by one-more** [comment]
It is designed behavior
